Allow parsing $this return type in docblock
phpactor/phpactor pull request #1806
Opened 2022-07-19 08:39 UTC by vlada-dudr

This fixes part of #1802. With this little patch this is now recognized:
```php
<?php
/** @method $this bla() */
class a {}

$o = new a;
$r = $->bla(); // $r is of type a
```
I am not sure though, if it cannot have some implications for condititional types parsing.

2022-07-22 04:53 UTC, dantleech requested changes
I think this looks good, could you add some tests? a snapshot test in `lib/DocblockParser/Tests/Unit/Printer/this.test`?

```
/**
 * @method $this 
 */
---
Docblock: = 
 ElementList: = /**
 * 
    // whatever the output should be here as reported by PHPUnit
 */
```

and then, more importantly, a test for your exact use case:

in `lib/WorseReflection/Tests/Inference/types/this-return-type-in-docblock.test`

```
<?php
/** @method $this bla() */
class a {}

$o = new a;
$r = $->bla();
wrAssertType('a', $r);

2022-07-22 04:53 UTC, dantleech commented on lib/DocblockParser/Parser.php
> +        if ($this->ifType() or $this->tokens->if(Token::T_VARIABLE)) {
`||` instead of `or` as convention

2022-07-28 10:35 UTC, vlada-dudr commented
So I added some test as requested. Actually I added more and let them commented out for now, so it can be seen what more can be done.

2022-07-28 10:53 UTC, vlada-dudr commented on lib/DocblockParser/Parser.php
> +        if ($this->ifType() or $this->tokens->if(Token::T_VARIABLE)) {
done

2022-07-31 08:11 UTC, dantleech commented
have had a look at this -- I think it would be better for me to do https://github.com/phpactor/phpactor/issues/1823 which should fix this in a better way..

2022-08-22 20:49 UTC, dantleech commented
Will be fixed in #1855

2022-08-22 20:49 UTC, closed without merging

2022-08-23 18:06 UTC, dantleech commented
Cherry picked your fix and tests, should work now!